### ISSUE TITLE
Missing bundled wof-fileserver

### ISSUE THREAD

**Issue by dphiffer** [whosonfirst/whosonfirst-www-iamhere#12]
The README describes a bundled `wof-fileserver` binary that isn't present.

**Comment by thisisaaronland** [comment]
Yeah, that should be fixed shortly. I spotted that on the plane and have no idea why or how...

**Comment by thisisaaronland** [comment]
This should be fixed now. Basically the build script for dependencies (in iamhere) wasn't checking that the (dependency) repository actually existed before moving the existing binary to a backup file. Go, me!
